### ISSUE TITLE
GetKey ignores [Shift] (and AltGr)

### ISSUE THREAD

**Issue by benkeks** [blitz3d-ng/blitz3d-ng#13]
If I run [help/commands/2d_examples/GetKey.bb](https://github.com/blitz3d-ng/blitz3d-ng/blob/master/_release/help/commands/2d_examples/GetKey.bb) with the last version of the original Blitz3D, it takes into account whether modifier keys are pressed. For instance, pressing [A] yields 97 (lower-case `a`), and pressing [Shift]+[A] returns 65 (upper-case `A`). Compiling the same source with Blitz3D-NG for Windows, both [A] and [Shift]+[A] lead to 97 as output. This seems not to be intended; and as I don't know the users' keyboard layouts, there also is no easy way to implement the modifier key logic manually from within the BB source.

**Comment by benkeks** [comment]
(Re-reported by https://youtu.be/DPRK2DCu4-k?t=1h15m51s playing a game that I compiled with Blitz3D-NG.)

**Comment by kfprimm** [comment]
Hey, thanks for the bug report. I can take a look at this in the next couple of days.

Can you produce a simple code example that demonstrates the problem and paste it here? That will help be address the issue much more quickly.

**Comment by benkeks** [comment]
To reproduce the problem, user input is necessary. Example code derived from [help/commands/2d_examples/GetKey.bb](https://github.com/blitz3d-ng/blitz3d-ng/blob/master/_release/help/commands/2d_examples/GetKey.bb).

```blitz3d
Print "Please press [Shift] and [A] on your keyboard! ..."

While Not value
value = GetKey()
Wend 

Print "GetKey() returned value: " + value + " (which is '" + Chr(value) + "'). (Should return: 65)"
WaitKey()
End
```

**Comment by kfprimm** [comment]
@benkeks, looks like it was a simple fix. 

For an easy update, just download `runtime.d3d7.dll` and place it in the `bin/` directory of your existing install.

https://ci.appveyor.com/project/kfprimm/blitz3d-ng-gj3xh/build/job/a8d3ljjnnr4kekhg/artifacts
