### ISSUE TITLE
OpenGL doesn't work

### ISSUE THREAD

**Issue by MikeHart66** [blitz3d-ng/blitz3d-ng#15]
OpenGL doesn't work on Windows 10

**Comment by kfprimm** [comment]
Hi,

Can you be more specific? I've used it on Windows 10 with no issue.

Please outline the steps to recreate.

Thanks.

**Comment by MikeHart66** [comment]
Any example. Just switch to opengl and click run. You can see a icon trying to open in the taskbar but then it disappears. No window opens at all.
I will check tonight if i get an error message ftom the console or the system events.

**Comment by c0d3r9** [comment]
Me too.dx7 is okay.But opengl doesn´t work.
Thats all what i can see and it close after a second.
![grafik](https://user-images.githubusercontent.com/40706628/55196134-c2733400-51ae-11e9-8c18-8a8cfddce969.png)

**Comment by kfprimm** [comment]
As previously mentioned, I have no issue so you'll both need to give me a little more to work with.

Which version of Windows 10? How about your system specs?

**Comment by c0d3r9** [comment]
Windows 10 64bit   Laptop: ASUS X540L with Intel HD 5500 Desktop: Ryzen 5 2400G with Vega 11

**Comment by MikeHart66** [comment]
Windows 10 Pro 64bit (uptodate)
8 GB Ram
Ryzen 5 2400G GPU
ASUS GFX1050Ti Cerberus Video card (Driver version 397.64)
