### ISSUE TITLE
Linux: Cmake error

### ISSUE THREAD

**Issue by alexefu73** [blitz3d-ng/blitz3d-ng#30]
Hi dears,
I have downloaded blitz3d-ng-master to my platform (Feren OS-2021.10-64bit), and installed all requested libs and tools like cmake and ruby and its gems,  When I started run the following line:
`./bin/blitz3d config && make ENV=release`
It result in the following lines:
`
Generating stub for Graphics...
Generating stub for Blitz...
Generating stub for Timer...
Generating stub for Runtime...
Generating stub for Input...
Generating stub for System...
Generating stub for Blitz2D...
Generating stub for Sockets...
Generating stub for Unit Test...
Generating stub for Filesystem...
Generating stub for Audio...
Generating stub for ODE...
Generating stub for Stream...
Generating stub for Math...
Generating stub for String...
Generating stub for Blitz3D...
Generating stub for Standard IO...
Generating stub for Windows System...
Generating stub for Steamworks...
Generating stub for Bank...
Generating stub for Enet...
Generating stub for Userlibs...
Generating runtime Direct3D 7...
  win32...
  mingw32...
Generating runtime OpenGL...
  mingw32...
  macos...
  linux...
  ios...
  emscripten...
  win32...
  win64...
  mingw32...
Generating runtime Test...
  win32...
  mingw32...
  macos...
  linux...
  ios...
  android...
  emscripten...
  nx...
cmake -G Ninja -H. -Bbuild/linux/release -DBB_PLATFORM=linux -DBB_ENV=release -DCMAKE_TOOLCHAIN_FILE=src/llvm.cmake && (cd build/linux/release && cmake --build . -j 4 -- -k 0)
CMake Error at deps/zlib/CMakeLists.txt:7 (add_subdirectory):
  The source directory

    /home/khalidaf/Executables/blitz3d-ng-master/deps/zlib/tree

  does not contain a CMakeLists.txt file.

CMake Error at deps/zlib/CMakeLists.txt:8 (target_include_directories):
  Cannot specify include directories for target "zlib" which is not built by
  this project.

CMake Error at deps/zlib/CMakeLists.txt:9 (target_include_directories):
  Cannot specify include directories for target "zlibstatic" which is not
  built by this project.

CMake Error at deps/zlib/CMakeLists.txt:11 (set_target_properties):
  set_target_properties Can not find target to add properties to: zlibstatic

CMake Error at deps/zlib/CMakeLists.txt:14 (set_target_properties):
  set_target_properties Can not find target to add properties to: zlib

CMake Error at deps/zlib/CMakeLists.txt:15 (set_target_properties):
  set_target_properties Can not find target to add properties to: example

CMake Error at deps/zlib/CMakeLists.txt:16 (set_target_properties):
  set_target_properties Can not find target to add properties to: minigzip

CMake Error at deps/enet/CMakeLists.txt:1 (add_subdirectory):
  The source directory

    /home/khalidaf/Executables/blitz3d-ng-master/deps/enet/src

  does not contain a CMakeLists.txt file.

CMake Error at deps/enet/CMakeLists.txt:2 (target_include_directories):
  Cannot specify include directories for target "enet" which is not built by
  this project.

CMake Error at /usr/share/cmake-3.22/Modules/ExternalProject.cmake:2666 (message):
  error: could not find git for clone of LUAJIT_EXTERNAL
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/ExternalProject.cmake:3716 (_ep_add_download_command)
  deps/luajit/CMakeLists.txt:14 (ExternalProject_Add)

-- Configuring incomplete, errors occurred!
See also "/home/******/Executables/blitz3d-ng-master/build/linux/release/CMakeFiles/CMakeOutput.log".
make: *** [Makefile:43: build] Error 1
`
So, what is the wrong? What I'm missing?

Thank you so much,

**Comment by kfprimm** [comment]
Hi,

It appears git is not installed. Note `error: could not find git for clone` in the log.  It is required for the build. I can update the README to include this.

Thanks.
