### ISSUE TITLE
Error creating exe win32 dx7!

### ISSUE THREAD

**Issue by Cyndanera** [blitz3d-ng/blitz3d-ng#8]
I can't create a exe file it says the following error "Error creating executable"
![bandicam 2018-04-02 19-53-12-765](https://user-images.githubusercontent.com/25001333/38223247-8783c50a-36af-11e8-9ff8-8088136043d9.png)

**Comment by Cyndanera** [comment]
Please help? please reply when you can, thanks. :)

**Comment by kfprimm** [comment]
This has been sorted in the latest build. Dump mistake on my part!
