### ISSUE TITLE
Hey buddy

### ISSUE THREAD

**Issue by PlasticCog** [blitz3d-ng/blitz3d-ng#9]
Hey pal, we're all impatiently waiting for some progress on this. https://www.syntaxbomb.com/index.php?topic=9.15

**Comment by kfprimm** [comment]
Hi,

This is a hobby project for me, so I work on it when I feel motivation. If you, or anyone else, would like to contribute, feel free to submit a PR and I will merge it.

Thanks!

**Comment by PlasticCog** [comment]
It's alive! Hey I was just joking, sorry if it wasn't obvious. Just wanted you to know there is a forum of people interested in the project. I don't have the skills to contribute to a project like this   :+1:
